version: "3"
services:
  api:
    build: .
    depends_on:
      - redis
      - postgres
    ports:
      - 8000:8000

    volumes:
      - .:/usr/src/app:ro

    entrypoint: [ "sh", "/usr/src/app/entrypoint.sh" ]

    environment:
      - REDIS_URL=${REDIS_URL}
      - BASE_URL=${BASE_URL}
      - DATABASE_URL=postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      - SECRET_KEY=${SECRET_KEY}
      - ALGORITHM=${ALGORITHM}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES}
      - SMTP_SERVER=${SMTP_SERVER}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_EMAIL=${SMTP_EMAIL}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - VERIFICATION_TOKEN_EXPIRE=${VERIFICATION_TOKEN_EXPIRE}
  redis:
    image: "redis:latest"
    restart: always
    ports:
      - "6379:6379"
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

    volumes:
      - postgres-db:/var/lib/postgresql/data
  celery:
    build: .
    command: celery -A celery_tasks.tasks worker --loglevel=info
    environment:
      - REDIS_URL=${REDIS_URL}
      - DATABASE_URL=postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
    depends_on:
      - redis
      - postgres


  celery-beat:
    build: .
    command: celery -A celery_tasks.tasks beat --loglevel=info
    environment:
      - REDIS_URL=${REDIS_URL}
    depends_on:
      - redis


volumes:
  postgres-db:


